"""empty message

Revision ID: 42b0e8a2e8cb
Revises: 586dedba0986
Create Date: 2021-12-11 18:32:13.801314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42b0e8a2e8cb'
down_revision = '586dedba0986'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_chores', sa.Column('last_turn', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_chores', 'last_turn')
    # ### end Alembic commands ###
